# spring configuration
spring:
   application:
      name: service-guestbook
      version: 1.0.0      
   profiles:
      active: development


---
# profile: common(default)
spring:
   cloud:
      config:
         enabled: true
---
# profile: development
spring:
   config:
      activate:
         on-profile: development
      import: optional:configserver:http://localhost:7777
---
# profile: production
spring:
   config:
      activate:
         on-profile: production
      import: optional:configserver:http://192.168.64.3:7777